USE shz58db;

DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS comments;
CREATE TABLE posts (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	user_id INT UNSIGNED,
	title VARCHAR(50),
	body TEXT,
	created DATETIME,
	modified DATETIME
);

CREATE TABLE users (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50),
	password TEXT,
	created DATETIME,
	modified DATETIME
);

CREATE TABLE reviews (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	user_id INT,
	title VARCHAR(100),
	body TEXT,
	rating INT,
	media VARCHAR(50),
	created DATETIME,
	modified DATETIME
);
CREATE TABLE messages (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	user_id INT,
	from_id INT,
	title VARCHAR(100),
	body TEXT,
	created DATETIME
);
CREATE TABLE comments (
	`id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	`review_id` INT NOT NULL ,
	`user_id` INT NOT NULL ,
	`body` TEXT NOT NULL ,
	`created` DATETIME NOT NULL
);
SHOW TABLES;

DESCRIBE posts;
DESCRIBE users;
